### PR TITLE
CFY-2649 fix failing test_local_agent_from_package test

### PR DESCRIPTION
**Pull request by m1keil**
appveyor environment change caused package install under wrong python (miniconda 64bit)

### CODE REVIEW

**Comment by dankilman** [comment]
what's with wheel's wheel?

**Comment by m1keil** [comment]
what do you mean?

**Comment by dankilman** [comment]
I don't remember why do we need to add a wheel?
The test seemed to work fine previously without it

**Comment by m1keil** [comment]
oh, right, but I think it's better to leave it there on the safe side. it
is possible python is old enough that it comes without wheel pre installed.

**Comment by dankilman** [comment]
I would rather remove all binaries from this repository altogether.
Considering this will require a lot of work fixing tests that will need to download things, I didn't do it yet.
With that said, I would prefer not adding new binaries if not absolutely necessary

**Comment by dankilman** [comment]
I would add to that, that I wish we hadn't added these binaries to begin with.
When we find the time, I think we should remove them and wipe the out of git's history altogether as currently, cloning this repo takes way more time then it should

**Comment by m1keil** [comment]
agree

**Comment by nir0s** [comment]
By the way, I already sent a pull request for removing those binaries from
the cli repo. Since then, there have been more commits of course. Once I'm
back, I can wipe both the the agent and cli repos.

**Comment by m1keil** [comment]
as far as i understand, this requires massive re-clone by anyone who might using the repo. @dankilman am I correct?

**Comment by dankilman** [comment]
Yes, but this will be for the greater good

**Comment by dankilman** [comment]
So, are you removing this wheel?

**Pull request merged**
